In [1]:
import pandas as pd
orderData=pd.read_csv('olist_orders_dataset.csv')

In [5]:
orderData.info()
orderData.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

(99441, 8)

In [6]:
orderData.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [7]:
orderData.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [8]:
orderData.groupby("order_status").size()

order_status
approved           2
canceled         625
created            5
delivered      96478
invoiced         314
processing       301
shipped         1107
unavailable      609
dtype: int64

In [19]:
orderData[orderData['order_delivered_customer_date'].isnull()].groupby('order_status').size()

order_status
approved          2
canceled        619
created           5
delivered         8
invoiced        314
processing      301
shipped        1107
unavailable     609
dtype: int64

In [32]:
orderData[orderData['order_delivered_carrier_date'].isnull()].groupby('order_status').size()

order_status
approved         2
canceled       550
created          5
delivered        2
invoiced       314
processing     301
unavailable    609
dtype: int64

Missing carrier date is mostly expected for orders not yet shipped/canceled

In [34]:
orderData[orderData['order_approved_at'].isnull()].groupby('order_status').size()

order_status
canceled     141
created        5
delivered     14
dtype: int64

Missing approval date is mostly expected for canceled orders, but 14 delivered orders are inconsistent

In [35]:
orderData[
    (orderData["order_status"] == "delivered") &
    (orderData["order_delivered_customer_date"] < orderData["order_delivered_carrier_date"])
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6437,a1abeb653a4d4cd1e142ccb8c82cd069,5f50465da00b7fed5dd1239f4ecf6e2c,delivered,2017-07-20 11:20:52,2017-07-21 06:43:14,2017-07-28 16:57:58,2017-07-25 19:32:56,2017-08-14 00:00:00
9553,383aa8b2724fe452d9ccd9934a8c628b,b1cb2f9d7a19480f3749e248db14d58f,delivered,2017-07-02 20:58:43,2017-07-02 21:10:20,2017-07-07 17:22:41,2017-07-06 14:27:51,2017-07-21 00:00:00
13487,cb1134f9010d242e9515ad1c78ec0c39,2fd33ac77677bd214b1882868317eeed,delivered,2017-07-16 12:35:34,2017-07-18 06:03:50,2017-07-20 19:22:02,2017-07-19 14:13:28,2017-08-08 00:00:00
14474,dceb62e8fa94b46006c9554fed743df0,2721900eb4e0f1cc2c836dd7bc1b1e11,delivered,2017-07-20 20:58:05,2017-07-22 11:45:11,2017-08-01 18:23:30,2017-07-26 18:09:10,2017-08-11 00:00:00
19268,5f9d46795c3126674e52becb3a1a517f,79287bcaafdde5c793b996fc40bb7d9f,delivered,2017-07-18 11:48:20,2017-07-18 12:03:29,2017-07-20 23:03:42,2017-07-20 18:52:41,2017-07-31 00:00:00
21338,8c78d01de3a9009e23d6877a7cc9be20,6cd7106899e59a1fbd0622d5f1efedf4,delivered,2016-10-08 15:36:50,2016-10-08 18:13:44,2016-10-26 11:41:53,2016-10-25 17:51:46,2016-11-30 00:00:00
22520,b27af682321527a6349f1761eb3f360c,9859dd92e872dbaa60ca3cd5f0d7ad07,delivered,2017-06-14 20:17:04,2017-06-14 20:30:08,2017-06-27 14:51:54,2017-06-26 15:45:35,2017-07-14 00:00:00
25393,1cc3ae63caffff2d6c3ee3e78e074acf,01c843a2c0600def0b7693dba47af460,delivered,2017-08-07 21:35:22,2017-08-08 21:45:15,2017-08-10 18:28:56,2017-08-10 18:05:38,2017-08-25 00:00:00
25646,e37f11cae9985ca58f0b56f268720537,3947a361301f2ff0f3223159a0f2701c,delivered,2017-07-26 11:46:34,2017-07-27 10:10:16,2017-08-01 18:17:47,2017-07-31 17:49:56,2017-08-24 00:00:00
27470,fa3e37584f4fdb1ded0e0de700dfcb4e,63be4feff10a0b1d85f2cfbf10df9754,delivered,2017-07-30 19:32:23,2017-07-30 19:45:09,2017-08-09 18:18:43,2017-08-01 21:13:01,2017-08-18 00:00:00
34939,c1e2bf2b7dd3309f2f5356c6b63968fa,e37d47e7eec62f08dc5deecc7d5532d6,delivered,2017-02-10 10:19:10,2017-02-10 10:30:13,2017-03-02 17:34:26,2017-02-14 15:15:57,2017-03-15 00:00:00
41636,b866af202be0692766081310cd4085e1,d1800078046ed2e5ae1b0792b695c56e,delivered,2017-01-27 14:59:17,2017-01-27 15:30:46,2017-02-20 02:32:08,2017-02-15 03:53:46,2017-04-17 00:00:00
45302,29941903985f944b0ffc49c479c1547d,b56ee98181afc3948a758d73a08423de,delivered,2017-05-29 16:16:50,2017-05-29 16:25:16,2017-06-09 15:07:29,2017-06-02 11:09:16,2017-06-23 00:00:00
49933,76458889992169d3135b264dc13aec67,999196dca58a3db3d966d8f148532010,delivered,2016-10-07 10:05:16,2016-10-07 11:24:43,2016-10-26 11:43:06,2016-10-20 18:03:17,2016-11-29 00:00:00
50373,0922ee1619de7b995648e5a8407afb91,8dab637615e9eae6d33ef5e48644d6d3,delivered,2017-07-11 10:45:44,2017-07-11 10:55:15,2017-07-14 12:41:34,2017-07-12 20:49:42,2017-08-14 00:00:00
58428,fbffbaaa30f4077e87ec6acdb835b278,a31e61974efff601345e65e5d6b7ff31,delivered,2017-07-30 17:58:26,2017-07-31 07:05:07,2017-08-04 20:04:17,2017-08-03 20:30:00,2017-08-18 00:00:00
68312,3ee6694bb99d5a6db0deceffcd099597,127237a4aa0bd9ecc09015f781c9fc27,delivered,2017-07-07 11:22:13,2017-07-07 12:25:07,2017-07-11 18:15:40,2017-07-11 17:41:26,2017-07-20 00:00:00
71227,19feb5627c41ea1b36a8e50a469b3644,b8097c8f0c1f58ab56a53812a446a898,delivered,2016-10-07 17:09:56,2016-10-07 17:32:09,2016-10-26 11:42:05,2016-10-20 19:07:54,2016-12-01 00:00:00
74967,d5558a097766363b8e76b38c43332e8a,49a4fe701c3d30eac6c180908e665ebb,delivered,2017-02-04 19:01:33,2017-02-04 19:31:12,2017-02-15 08:55:26,2017-02-10 07:58:32,2017-03-01 00:00:00
76120,771c4f1f521f462e4b95619e648aaeab,d424b3ce4c850247e8c84ff8752de868,delivered,2017-03-22 20:15:15,2017-03-22 20:15:15,2017-03-30 13:14:34,2017-03-28 17:28:32,2017-04-12 00:00:00
78556,ea1dcb4757a844d2642547797bd5feb0,4999e129610251dec1e6fb712dc15171,delivered,2017-07-18 13:38:29,2017-07-18 13:50:23,2017-07-27 19:21:31,2017-07-25 19:43:10,2017-08-15 00:00:00
90373,99ad48402644a3968f2481defdc57947,abc709e0756f508111c68314b00cec25,delivered,2017-08-07 16:36:51,2017-08-07 17:20:06,2017-08-12 00:03:35,2017-08-10 21:22:31,2017-09-05 00:00:00
95634,f688669f48063536e082bb32d634cd46,691d28310063e5b36b732b117f2bcfc0,delivered,2016-10-07 10:28:56,2016-10-11 04:56:13,2016-10-21 18:02:40,2016-10-20 20:33:27,2016-11-29 00:00:00

 Some delivered orders have inconsistent timestamps: customer delivery is earlier than carrier handover

In [39]:
orderData[
    (orderData["order_status"] == "delivered") &
    (orderData["order_delivered_customer_date"] > orderData["order_estimated_delivery_date"])
].shape[0]

7826

 8.1% of delivered orders were delivered after the estimated delivery date

In [41]:
orderData.describe(include="object")

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-08-02 12:05:26,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-08 19:36:48,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

Each order_id is unique, indicating one row per order

In [42]:
orderData['order_id'].duplicated().sum()

np.int64(0)

In [93]:
date_columns = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_columns:
    orderData[col] = pd.to_datetime(orderData[col])

In [95]:
orderData.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [96]:
orderData[
    (orderData["order_status"] == "delivered") &
    (orderData["order_delivered_customer_date"].isnull())
].shape

(8, 8)

## order_items

In [ ]:
order_item =pd.read_csv('olist_order_items_dataset.csv')

In [44]:
order_item.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [47]:
order_item.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [54]:
order_item.describe()

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [63]:
order_item.groupby('order_id')['order_item_id'].size().value_counts().sort_index()

order_item_id
1     88863
2      7516
3      1322
4       505
5       204
6       198
7        22
8         8
9         3
10        8
11        4
12        5
13        1
14        2
15        2
20        2
21        1
Name: count, dtype: int64

In [99]:
order_item['shipping_limit_date'] = pd.to_datetime(
    order_item['shipping_limit_date']
)

In [100]:
order_item.dtypes

order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
dtype: object

In [104]:
order_item.duplicated().sum()

np.int64(0)

In [139]:
order_item[['price', 'freight_value']].describe()

               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000

In [141]:
(order_item['price'] < 0).sum()

np.int64(0)

In [143]:
(order_item['freight_value'] < 0).sum()

np.int64(0)

## Customers

In [65]:
customer=pd.read_csv('olist_customers_dataset.csv')

In [66]:
customer.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [67]:
customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [144]:
customer['customer_unique_id'].isna().sum()

np.int64(0)

In [71]:
customer.groupby('customer_unique_id').size().value_counts()

1     93099
2      2745
3       203
4        30
5         8
6         6
7         3
9         1
17        1
Name: count, dtype: int64

Why is repeat purchasing relatively low, and how can Olist increase customer retention/repeat purchases?

In [107]:
for city in customer['customer_city'].unique():
    print(city)

franca
sao bernardo do campo
sao paulo
mogi das cruzes
campinas
jaragua do sul
timoteo
curitiba
belo horizonte
montes claros
rio de janeiro
lencois paulista
caxias do sul
piracicaba
guarulhos
pacaja
florianopolis
aparecida de goiania
santo andre
goiania
cachoeiro de itapemirim
sao jose dos campos
sao roque
camacari
resende
sumare
novo hamburgo
sao luis
sao jose
santa barbara
ribeirao preto
ituiutaba
taquarituba
sao jose dos pinhais
barrinha
parati
dourados
trindade
cascavel
fortaleza
brasilia
pelotas
porto alegre
salto
jundiai
cacapava
sao vicente
uberlandia
botelhos
sao goncalo
araucaria
nova iguacu
areia branca
campos dos goytacazes
sao carlos
itajuba
cruz das almas
vassouras
feira de santana
niteroi
sobral
divinopolis
paraiba do sul
paulista
carapicuiba
bom principio
astolfo dutra
marialva
sao jose do rio preto
cabo frio
contagem
cafeara
sao joaquim da barra
foz do iguacu
suzano
timbo
camboriu
nova bassano
rio grande
braganca paulista
barra do garcas
embu
urussanga
silvianopolis
gameleiras
belem
pocos de caldas
santos
piracaia
sinop
guaruja
barueri
feliz
jambeiro
ipatinga
tupa
blumenau
moncoes
balneario camboriu
vargem grande
rio brilhante
eugenopolis
paulinia
apucarana
recife
osasco
valinhos
manaus
cidreira
santiago
sao sepe
alta floresta
jaboatao dos guararapes
ibatiba
hortolandia
cotia
macae
saudades
macapa
salto de pirapora
taboao da serra
bom jesus
santa cruz do rio pardo
diadema
santa ines
serrinha
votorantim
itatiaia
duque de caxias
varre-sai
vila velha
mangaratiba
atibaia
salvador
maceio
birigui
petropolis
sao pedro
jaguariaiva
franco da rocha
pindamonhangaba
irati
ribeira
barbacena
limoeiro
espigao do oeste
belford roxo
coronel fabriciano
itanhaem
bebedouro
americana
uba
arapongas
vinhedo
itajai
bauru
pradopolis
aripuana
guaratinga
ponta pora
aracatuba
volta redonda
maringa
araraquara
matipo
santo antonio da patrulha
barra mansa
diamantina
mairinque
capitao leonidas marques
sao sebastiao do paraiso
rosario do sul
itaguai
paraopeba
guarapuava
crisolita
pirai
linhares
agudos
sao joao de meriti
navegantes
pirassununga
faxinal dos guedes
criciuma
nova venecia
passo fundo
ibia
manhuacu
altamira
aperibe
cuiaba
canoas
cubatao
campo limpo paulista
cambe
itaquaquecetuba
sao caetano do sul
sao goncalo do rio abaixo
rolandia
tres coracoes
cacapava do sul
sao joao nepomuceno
leme
araras
cortes
brusque
montenegro
itaberai
santa rosa de viterbo
agua fria de goias
marau
curvelo
juiz de fora
mogi-guacu
guaratingueta
paranagua
lins
campo bom
sertaozinho
tres lagoas
jau
campos de julio
saquarema
artur nogueira
uaua
jandira
concordia
nova friburgo
sorocaba
ponte nova
araquari
muriae
nova lima
inhumas
italva
tres rios
santa maria
itagiba
paracatu
xaxim
laranjeiras do sul
itapiuna
formosa
ivoti
juazeiro
ponta grossa
campina grande
maua
salgueiro
lorena
toledo
sao pedro da aldeia
vianopolis
arapiraca
porto seguro
ariquemes
presidente getulio
rio negro
ribeirao pires
sao jose da coroa grande
agua doce do norte
anapolis
guararapes
farroupilha
almenara
rio das ostras
gravatai
brumado
marilia
itabira
claudia
para de minas
miguelopolis
terra roxa
araguari
lages
embu das artes
limeira
taubate
santa fe do sul
caieiras
carangola
chapada do norte
loanda
passa tres
aracoiaba da serra
itaborai
vitoria
sao bento do sul
indaiatuba
boituva
teresopolis
pinhalzinho
petrolina
natal
barreiras
januaria
ipiabas
firminopolis
joinville
mococa
valenca
sao miguel do oeste
jales
rio formoso
angra dos reis
alfredo chaves
itapetinga
gurupi
nucleo residencial pilar
coromandel
charqueada
itau de minas
ibiruba
bertioga
ipiau
matozinhos
teresina
entre rios
juina
mairipora
marechal candido rondon
avare
icem
sao sebastiao
serra
mirassol
taperuaba
alfenas
leopoldina
sao joao da boa vista
parnamirim
teixeira de freitas
joao pessoa
chacara
rio novo do sul
guapore
rio branco
ferraz de vasconcelos
petrolandia
araruna
gravata
alegre
londrina
senhor do bonfim
santana de parnaiba
piratininga
monte carmelo
ipiranga
jacarei
picos
una
taguai
peabiru
conquista
bicas
forquilha
guaicara
santa vitoria
adamantina
rio claro
sao jose de uba
sorriso
aracaju
conselheiro lafaiete
taguatinga
tiangua
paranaiba
david canabarro
itarare
cajueiro
cruzeiro
santa cruz do sul
presidente epitacio
castanhal
cariacica
bom jesus dos perdoes
urucurituba
olinda
sao jose do rio pardo
guapimirim
vargem grande paulista
chapeco
videira
canapi
pontal do parana
bento goncalves
caceres
bituruna
sao bento do sapucai
mage
forquilhinha
itaberaba
gramado
guacui
pato branco
itanhem
palmas
bage
francisco morato
cosmopolis
carmo
armacao dos buzios
santa maria da vitoria
pedro leopoldo
tres marias
santo antonio de padua
porto feliz
gaspar
palhoca
pouso alegre
guaiuba
fraiburgo
aurea
botucatu
corumba
cajamar
queimados
sao jorge do ivai
nova laranjeiras
guaxupe
osvaldo cruz
ivora
anaurilandia
caraguatatuba
regeneracao
bilac
faxinal
pedro velho
uberaba
viamao
cachoeira de minas
coelho neto
itajobi
carmo do rio claro
marica
campo novo do parecis
boa vista
ipameri
carlos barbosa
anicuns
rio bananal
lavras da mangabeira
balsamo
guariba
sao vendelino
campo mourao
aracati
santo antonio do descoberto
santo amaro da imperatriz
betim
vicosa
dom eliseu
campo largo
santa rosa de lima
quissama
mirandopolis
itapevi
francisco beltrao
dias d'avila
novo horizonte
poa
querencia
campo grande
pedreira
pariquera-acu
itabaianinha
pitangui
araruama
campo formoso
guanambi
itapolis
pederneiras
itabirito
itaipava
arroio do sal
glaura
lagoa vermelha
mantena
peruibe
tubarao
bonfim
alvorada
patrocinio
mineiros
itabuna
tijucas
santo antonio de jesus
canarana
itapecerica da serra
nova prata do iguacu
treze tilias
anchieta
quatigua
iturama
tres de maio
santa rita do passa quatro
porto esperidiao
bonfim paulista
cajuru
cacador
paragominas
boa esperanca do sul
tres pontas
juazeiro do norte
bambui
comendador levy gasparian
sao miguel do aleixo
palmeira dos indios
cerquilho
saudade do iguacu
ipaussu
alto paraiso de goias
santa isabel
quirinopolis
caruaru
casimiro de abreu
chavantes
ecoporanga
cachoeira paulista
rio verde
maracanau
canoinhas
ituverava
buriti dos lopes
rio do antonio
guaranta
santa luzia
tucurui
paranavai
pinhais
governador valadares
trajano de moraes
caete
abaetetuba
lavras
coronel joao sa
divino
macaubas
lucelia
brejo da madre de deus
carai
corbelia
varginha
ouro preto
prado
colniza
piuma
rancharia
barretos
eunapolis
floresta
sao jose do norte
rio bonito
vargem bonita
monte mor
valente
balsas
nhandeara
lauro de freitas
osorio
machado
sao leopoldo
soledade
assis
guarapari
santo antonio do caiua
esteio
cambuci
campina grande do sul
baixo guandu
fernao
ibitinga
santa cruz das palmeiras
vila muriqui
sao mateus
piracuruca
cordeiro
cachoeira do sul
barra do pirai
castro
ico
sete lagoas
itumbiara
aluminio
jatai
frederico westphalen
goioere
sao jose da tapera
porto uniao
cocalinho
curitibanos
campos novos
ubatuba
monte santo de minas
ribeirao das neves
sao simao
urutai
itaobim
liberdade
arcos
ribeirao
patos de minas
penapolis
eusebio
cordeiros
victor graeff
santa rita do araguaia
poxoreu
ananas
conceicao dos ouros
alagoinhas
sao joao da barra
lindoia
bonfinopolis
ibiam
morungaba
andradina
tatui
mata verde
cornelio procopio
itapipoca
queluz
godoy moreira
iracemapolis
buritizeiro
xique-xique
uruacu
japi
itauna
sao francisco de assis
pitangueiras
ze doca
dracena
cachoeiras de macacu
barauna
formiga
rodeio
jequie
juvenilia
poco fundo
amparo
lauro muller
japeri
ourinhos
lagoa dos gatos
embu-guacu
nossa senhora do remedio
tambau
orlandia
bananeiras
sao joao do manhuacu
sarandi
congonhas
boa esperanca
sandolandia
garca
descalvado
guaracai
aruana
inga
taio
gaurama
praia grande
janauba
nova monte verde
mongagua
monte alto
sao joao do piaui
primavera do leste
seropedica
indaial
teofilo otoni
santa terezinha
planaltina
caravelas
muritiba
itatiba
piumhii
pitanga
capelinha
ipero
tarabai
aparecida do taboado
maioba
monnerat
sao lourenco do sul
biguacu
venda nova do imigrante
arapoti
fazenda rio grande
senges
aracruz
canela
porto franco
veranopolis
candiota
carmo do paranaiba
itacare
desembargador otoni
joanopolis
registro
ipiranga do norte
felipe guerra
dumont
itapetininga
bom despacho
lagoa santa
estacao
panorama
palmares
prata
santa adelia
iguaba grande
sarzedo
dourado
alcinopolis
limoeiro do norte
ibiraci
ilhabela
icara
paiva
batatais
formoso do araguaia
itapaci
fernandopolis
miguel pereira
tocos
campos do jordao
catalao
sao jose da lapa
marituba
arapora
turvo
rubiataba
guaruja do sul
pedra bela
perdizes
jesuania
antonio carlos
itapecerica
monte belo
mossoro
piraju
encruzilhada do sul
igaratinga
sao luis de montes belos
santa rosa
lagoinha
redentora
cuite
coxim
lucas do rio verde
ibirataia
olimpia
cedro
mario campos
umuarama
nova xavantina
sao borja
aguai
itapira
uniao da vitoria
nova odessa
itapuranga
nova cruz
apuiares
almirante tamandare
correia pinto
itamarandiba
juscimeira
ipora
cedro de sao joao
santa barbara d'oeste
sao joao da urtiga
valparaiso de goias
jussara
capao da canoa
araxa
campo belo
monte aprazivel
bom jesus do querendo
socorro
catanduva
monte castelo
tabatinga
bayeux
ijui
tangara da serra
campos borges
palma
minacu
miracema
taruma
sao francisco do sul
cedral
camaragibe
lajeado
cerqueira cesar
frutal
igarata
novo gama
sapucaia do sul
juquitiba
terra boa
joao monlevade
porangatu
formosa da serra negra
rafard
rainha do mar
pontal
rio do sul
nilopolis
maracaju
santo augusto
banabuiu
buenopolis
barbalha
quintana
chorrocho
votuporanga
poco verde
cipo-guacu
santarem
santa clara do sul
ibiuna
capivari
arraias
patos
sao francisco do guapore
vitoria da conquista
urucuca
vacaria
campos altos
nossa senhora do socorro
cruzeiro do sul
cataguases
varzea grande
santa rita do sapucai
jaboticabal
ilha comprida
brasilia de minas
moreno
capanema
tombos
espumoso
ouro branco
valenca do piaui
igrejinha
engenheiro coelho
parauapebas
afonso claudio
sao bernardo
salto do jacui
pires do rio
astorga
medina
porto ferreira
aracariguama
hidrolandia
virginopolis
soledade de minas
casca
sapiranga
angatuba
ibirapua
itupeva
espera feliz
penedo
ibirite
miracatu
francisco santos
paracambi
cardoso
floriano
rondonopolis
barra de sao francisco
lavinia
guajara-mirim
guimaraes
sao tome
medianeira
conceicao das pedras
rinopolis
capim grosso
guaira
euclides da cunha paulista
lagoa da prata
nanuque
luis antonio
senador firmino
viradouro
itabera
cambara
sananduva
tapera
tupaciguara
colombo
ananindeua
coribe
rio doce
mogi mirim
tocos do moji
beberibe
formosa do rio preto
claudio
rio paranaiba
humberto de campos
camocim de sao felix
santo antonio de posse
mesquita
passa quatro
belo oriente
alto araguaia
igarassu
porto velho
cajazeiras
garopaba
rio azul
dois corregos
sooretama
cruzeiro do oeste
nazare paulista
riversul
iguaracu
maracas
parana
reboucas
ametista do sul
itu
cacu
vespasiano
lindolfo collor
sao lourenco
santana do sobrado
cafelandia
ibiapina
schroeder
sao joao do oriente
matao
itanhandu
santo angelo
capinopolis
colatina
nova mutum
munhoz de melo
ibate
unai
medeiros neto
anta
ouroeste
central
nova independencia
itapema
sao jose do cedro
camutanga
ipumirim
cristalia
andira
panelas
comodoro
domingos martins
tangua
sao gotardo
araguaina
ilheus
louveira
imbituba
ouricuri
itatinga
santo cristo
arraial d'ajuda
piracanjuba
russas
lambari
vargem alta
sacra familia do tingua
assis chateaubriand
lago da pedra
unistalda
sao joao evangelista
paramirim
goias
paracuru
cruz alta
presidente bernardes
pains
sao goncalo do rio preto
jacinto machado
sobralia
maraba
paraibuna
toropi
jauru
cristalandia
castelo do piaui
ibipora
presidente dutra
vera cruz
paulo frontin
rio grande da serra
ocaucu
xinguara
guaranesia
extrema
braco do rio
timon
ipora do oeste
santa cruz da conceicao
ivate
erechim
palmeiras
guarani
tremembe
rio preto
tucunduva
sao tiago
prados
aguas belas
xambre
arvorezinha
sao martinho
antonio prado
paulo lopes
maravilha
jeremoabo
navirai
itubera
uruguaiana
ji-parana
tabuleiro
campo ere
california da barra
nova londrina
divinopolis de goias
uruana
presidente prudente
sao joao de petropolis
luis eduardo magalhaes
matupa
quatro barras
costa rica
novo oriente
capao bonito
taua
igarapava
jacui
aragarcas
independencia
lagoa de velhos
cantagalo
paulo afonso
caldas novas
dores de guanhaes
aguas de lindoia
sao jose da bela vista
montanha
santana
jaci
feira nova
cachoeira da prata
carazinho
cunha
bom jesus da penha
santa isabel do para
caxias
pacaembu
mucuri
santaluz
tocantinopolis
aruja
palmeira
araripina
bom conselho
piripa
ponto belo
mangueirinha
monte siao
cianorte
aguas da prata
catende
urupes
vila rica
macedonia
sao joao
vila nova
sao francisco de itabapoana
esmeraldas
portela
borborema
santa cruz cabralia
palmital
cicero dantas
cachoeira alta
niquelandia
paraguacu paulista
ilha solteira
santo antonio do leverger
girua
serranopolis de minas
morada nova
sao pedro da agua branca
jacarezinho
ibirarema
caraiba
gaucha do norte
matias barbosa
santa tereza do oeste
aguas de sao pedro
candeias
varzea paulista
pilar do sul
macau
jandaia do sul
jeceaba
vila dos cabanos
carinhanha
arace
abreu e lima
salto do lontra
santo expedito do sul
tiete
juatuba
bom jesus da lapa
nova santa rosa
garanhuns
abaete
lajedo
barra do tarrachil
carandai
tupassi
saubara
barra velha
itaja
coroata
braganca
rio pardo de minas
mamanguape
duere
anage
santo antonio do jacinto
cesario lange
sao raimundo nonato
escada
cangucu
apore
cajapio
sao gabriel
santa albertina
capao da porteira
nova brasilandia d'oeste
cordeiropolis
dois irmaos
canhotinho
barra do corda
espirito santo do pinhal
xanxere
mansidao
guararema
mostardas
rio do campo
currais novos
agua branca
crateus
garibaldi
estancia velha
papanduva
miranda do norte
itambe
senador canedo
guaraniacu
paraisopolis
antonina
tapejara
cabreuva
cassia
mata roma
balneario pinhal
cajati
aracoiaba
monte alegre de minas
nova araca
teotonio vilela
jaguariuna
aguas formosas
pojuca
guapo
anastacio
aguas lindas de goias
agua boa
jaguaribe
senador jose porfirio
itapirapua
hidrolina
vista alegre
iacu
palmeira das missoes
toritama
prudente de morais
itapejara d'oeste
humaita
sao thome das letras
passos
cristalina
benedito novo
santo amaro
marinopolis
divinolandia de minas
itutinga
santana do paraiso
itaperuna
lupionopolis
itirapina
alto paraiso
visconde do rio branco
taiobeiras
eloi mendes
campina verde
mae do rio
orizona
sapopema
boa vista do sul
teutonia
nepomuceno
paula candido
itapeva
aurora
igapora
bom jesus do galho
bezerros
piranga
pereira barreto
itamari
itaguacu da bahia
lindoia do sul
mirassol d'oeste
capitolio
mariana
eldorado do sul
sao miguel arcanjo
aparecida
encantado
bastos
santo antonio do sudoeste
jesuitas
ibirama
chapada dos guimaraes
piritiba
aimores
madre de deus
uruana de minas
gramado xavier
planalto
goitacazes
presidente venceslau
buri
medeiros
balneario picarras
cacoal
bandeirantes
santa cecilia
alegrete
sao joaquim
maria da fe
guarai
colinas
raposos
palestina
sao bento do una
quitandinha
pompeia
colonia leopoldina
rio branco do sul
ituporanga
quilometro 14 do mutum
sao jose do egito
sao francisco do humaita
simonesia
lagoa grande
guara
penha
iguai
remanso
sao miguel do gostoso
pongai
gandu
alto alegre do maranhao
otacilio costa
lajinha
ruy barbosa
santana do araguaia
triunfo
viana
sao jose de ribamar
murici
arapoema
cuite velho
santana do manhuacu
nazareno
campo alegre
candelaria
pranchita
augusto pestana
barcarena
laguna
parnaiba
tanabi
paty do alferes
seara
itinga
mossamedes
andradas
santana do mundau
papucaia
nova prata
angelo frechiani
nova serrana
cristina
itaporanga
areal
sao joao del rei
salesopolis
marmeleiro
conceicao do para
juti
nova alvorada do sul
campinorte
martinopolis
pirapora
paraguacu
barra dos coqueiros
anta gorda
miguel calmon
cabeceira grande
sao cristovao do sul
ilopolis
curiuva
resplendor
itai
monte alegre do sul
sao sebastiao da grama
mafra
araci
buritama
luiziania
buritis
morrinhos
sao lourenco da mata
santa cruz
tuiuti
nova cantu
pinheiral
trombudo central
acu
cristal
parambu
sumidouro
lagarto
putinga
caxambu
presidente castello branco
capinzal
nova veneza
andorinha
telemaco borba
santa gertrudes
nova era
itapiranga
camamu
rosana
cachoeirinha
alem paraiba
itamaraju
acopiara
barra de sao joao
arrozal
santana do livramento
itabela
nova andradina
manhumirim
olaria
caninde
itaqui
tucuma
santa isabel do ivai
goianira
jacutinga
bonito de santa fe
valao do barro
milagres
piedade
conceicao da barra
torrinha
engenheiro passos
cristais
canaa dos carajas
alto parana
senador cortes
bom jesus do itabapoana
frei inocencio
luziania
taiuva
conceicao do mato dentro
orindiuva
zortea
brumadinho
ceu azul
campina da lagoa
santo antonio do jardim
primavera
formoso
portao
porto amazonas
sinimbu
barra bonita
apiai
porto real
umbauba
boqueirao do leao
sabara
terra nova do norte
conservatoria
juquia
joacaba
sao luiz gonzaga
camapua
igarape
santa ernestina
colonia vitoria
itamonte
sao joao d'alianca
corumbaiba
serra negra
general carneiro
porciuncula
paranaita
imperatriz
posse
fortuna
vermelho
trindade do sul
munhoz
joao pinheiro
bocaiuva
brejo dos santos
itororo
duartina
campestre da serra
cabedelo
dores do indaia
caridade
pato bragado
jardinopolis
ibema
sobradinho
pinhao
carapebus
inaciolandia
novo repartimento
paicandu
guaranta do norte
coxilha
ipojuca
brauna
iguatu
morro do chapeu
cerejeiras
barras
irapuru
diamante d'oeste
aparecida de sao manuel
vilhena
sao pedro do ivai
sirinhaem
mato verde
paraiso das aguas
mirante da serra
rio novo
pirapora do bom jesus
vazante
conceicao do castelo
junqueiropolis
simplicio mendes
bom jardim de minas
tupi paulista
campestre do maranhao
santa vitoria do palmar
dois vizinhos
pirapetinga
witmarsum
itapage
simoes filho
surubim
laranjal
nova esperanca
deputado irapuan pinheiro
aquidaba
arroio dos ratos
reserva do cabacal
cantanhede
cachoeira de pajeu
rio pardo
esplanada
engenheiro paulo de frontin
bom jesus do araguaia
sao geraldo
catu de abrantes
jacinto
piranguinho
piedade de caratinga
capela de santana
santa maria de jetiba
carpina
nova ponte
sao jose de mipibu
urania
sao jose do ouro
sao luis do quitunde
pancas
santos dumont
delfinopolis
missal
auriflama
quadra
quedas do iguacu
campinacu
caririacu
dom silverio
sao jose do calcado
ibipeba
araguatins
araujos
bonfinopolis de minas
angicos
santo antonio das missoes
quixada
palmitinho
presidente kennedy
analandia
nova granada
mercedes
canapolis
tapes
vere
sao felix do xingu
cariri do tocantins
dormentes
mutum
sao jose do xingu
quatis
caratinga
paranapanema
tramandai
sao jose da barra
cambui
itaju
pilao arcado
jaguaracu
mimoso de goias
sao gabriel do oeste
oros
araputanga
ceara-mirim
indianopolis
caucaia
crisopolis
quevedos
araguapaz
estiva gerbi
nuporanga
sardoa
chapadao do ceu
santa terezinha de itaipu
cacule
machacalis
camacan
roseira
itaiopolis
barra do bugres
sousa
castilho
potirendaba
tarumirim
mendes
campo verde
bom jardim
ivaipora
santana do serido
iconha
conceicao do araguaia
abatia
amelia rodrigues
candido rodrigues
coronel vivida
vitoria de santo antao
ielmo marinho
cosmorama
arroio do meio
urupa
sao sebastiao da boa vista
varzedo
piranhas
corumba de goias
saltinho
dianopolis
espigao
salmourao
quixere
esperanca
bariri
girau do ponciano
joao lisboa
porecatu
lima duarte
malacacheta
umburatiba
santa margarida
sao mateus do sul
arapei
avanhandava
camanducaia
paraiso
mirai
ribeirao do pinhal
upanema
domiciano ribeiro
promissao
conselheiro pena
uruoca
vargem grande do sul
brotas
sao joao batista do gloria
alexania
juranda
fartura
mateus leme
monte azul
santa cruz do capibaribe
macaiba
quata
teodoro sampaio
almino afonso
vargem alegre
arroio grande
jaboticatubas
parelhas
alto alegre do iguacu
joaquim tavora
bataypora
bombinhas
fernando prestes
rio largo
itabaiana
sideropolis
utinga
rondon do para
mirante do paranapanema
oriente
sapucai-mirim
tres passos
horizonte
silva jardim
sanharo
eldorado
itacoatiara
acreuna
crato
pimenta bueno
sitio novo do tocantins
ipira
sao jose do vale do rio preto
varzea da palma
sao gabriel da palha
holambra
ubata
mar vermelho
governador celso ramos
bandeira
turmalina
tabapora
novo cabrais
taquaritinga do norte
castelo
pirajui

In [108]:
customer.duplicated().sum()

np.int64(0)

In [109]:
customer['customer_state'].unique()

array(['SP', 'SC', 'MG', 'PR', 'RJ', 'RS', 'PA', 'GO', 'ES', 'BA', 'MA',
       'MS', 'CE', 'DF', 'RN', 'PE', 'MT', 'AM', 'AP', 'AL', 'RO', 'PB',
       'TO', 'PI', 'AC', 'SE', 'RR'], dtype=object)

## Product

In [72]:
products=pd.read_csv("olist_products_dataset.csv")

In [73]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [74]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [75]:
products[products['product_category_name'].isnull()].head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0

In [145]:
products[
    (products['product_name_lenght'] < 0) |
    (products['product_description_lenght'] < 0) |
    (products['product_photos_qty'] < 0) |
    (products['product_weight_g'] < 0) |
    (products['product_length_cm'] < 0) |
    (products['product_height_cm'] < 0) |
    (products['product_width_cm'] < 0)
]

Empty DataFrame
Columns: [product_id, product_category_name, product_name_lenght, product_description_lenght, product_photos_qty, product_weight_g, product_length_cm, product_height_cm, product_width_cm]
Index: []

In [114]:
products[products['product_weight_g']==650.0]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
30,47859fca9dd7485cbd93c3e8993bb74f,cama_mesa_banho,45.0,206.0,1.0,650.0,16.0,10.0,16.0
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
107,c33d78b97260227119fb2b71be168fca,cama_mesa_banho,39.0,170.0,1.0,650.0,27.0,10.0,22.0
234,c752f2bc46ad4b389290cf5828a1db62,beleza_saude,40.0,654.0,1.0,650.0,25.0,13.0,14.0
301,d294bd539d8c70342149beb38b767afc,relogios_presentes,50.0,295.0,1.0,650.0,13.0,11.0,12.0
...,...,...,...,...,...,...,...,...,...
32649,1d37ba8cc6a900b5b50ba1b5121f02e8,eletronicos,27.0,197.0,1.0,650.0,32.0,14.0,11.0
32690,01f2d77d8a63937c77c7128ce4bd2ada,automotivo,60.0,753.0,2.0,650.0,60.0,6.0,33.0
32796,3f030b63da680202be73077d29199e31,papelaria,47.0,74.0,1.0,650.0,36.0,14.0,44.0
32825,de8079863f52e090930c58a327e8c8e1,livros_importados,26.0,338.0,1.0,650.0,29.0,2.0,22.0
32915,d790fcd60d4743d309fedf7e7bb4c902,beleza_saude,39.0,811.0,1.0,650.0,50.0,5.0,30.0

In [110]:
products[
    products['product_category_name'].isna()
].isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                1
product_length_cm               1
product_height_cm               1
product_width_cm                1
dtype: int64

In [111]:
products['product_id'].duplicated().sum()

np.int64(0)

## Sellers

In [76]:
sellers=pd.read_csv('olist_sellers_dataset.csv')

In [77]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [78]:
sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [115]:
sellers['seller_id'].duplicated().sum()

np.int64(0)

## Reviews

In [79]:
reviews=pd.read_csv('olist_order_reviews_dataset.csv')

In [80]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [81]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [121]:
reviews['review_creation_date'] = pd.to_datetime(reviews['review_creation_date'])
reviews['review_answer_timestamp'] = pd.to_datetime(reviews['review_answer_timestamp'])

In [122]:
reviews.dtypes

review_id                          object
order_id                           object
review_score                        int64
review_comment_title               object
review_comment_message             object
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

In [120]:
reviews['review_score'].value_counts()

review_score
5    57328
4    19142
1    11424
3     8179
2     3151
Name: count, dtype: int64

## payments

In [82]:
payments=pd.read_csv('olist_order_payments_dataset.csv')

In [83]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [84]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [123]:
payments['payment_type'].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [126]:
pay=payments[payments['payment_type'] == 'not_defined']
pay

,order_id,payment_sequential,payment_type,payment_installments,payment_value
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0

In [128]:
orderData[orderData['order_id'].isin(pay['order_id'])][
    ['order_id', 'order_status']
]

                               order_id order_status
1130   00b1cb0320190ca0daa2c88b35206009     canceled
39919  4637ca194b6387e2d538dc89b124b0ee     canceled
40235  c8c528189310eaa44a745b8d9d26908b     canceled

In [129]:
clean_payments = payments[
    payments['payment_type'] != 'not_defined'
].copy()

## Geolocation

In [85]:
geolocation=pd.read_csv('olist_geolocation_dataset.csv')

In [86]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [87]:
geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [130]:
geolocation.duplicated().sum()

np.int64(261831)

In [132]:
geolocation.drop_duplicates().shape

(738332, 5)

In [135]:
geolocation['geolocation_state'].unique()

array(['SP', 'RN', 'AC', 'RJ', 'ES', 'MG', 'BA', 'SE', 'PE', 'AL', 'PB',
       'CE', 'PI', 'MA', 'PA', 'AP', 'AM', 'RR', 'DF', 'GO', 'RO', 'TO',
       'MT', 'MS', 'RS', 'PR', 'SC'], dtype=object)

## Translation

In [90]:
translation=pd.read_csv('product_category_name_translation.csv')

In [91]:
translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [92]:
translation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [136]:
translation.duplicated().sum()

np.int64(0)

In [ ]:
import urllib.parse
from sqlalchemy import create_engine

params = urllib.parse.quote_plus(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=localhost\\SQLEXPRESS;"
    "DATABASE=Olist;"  
    "Trusted_Connection=yes;"
)

engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

orderData.to_sql('orderData', con=engine, if_exists='replace', index=False)

In [ ]:
order_item.to_sql('order_item', con=engine, if_exists='replace', index=False)
payments.to_sql('payments', con=engine, if_exists='replace', index=False)
translation.to_sql('translation', con=engine, if_exists='replace', index=False)
reviews.to_sql('reviews', con=engine, if_exists='replace', index=False)
sellers.to_sql('sellers', con=engine, if_exists='replace', index=False)
geolocation.to_sql('geolocation', con=engine, if_exists='replace', index=False)
customer.to_sql('customer', con=engine, if_exists='replace', index=False)
products.to_sql('products', con=engine, if_exists='replace', index=False)

NameError: name 'product' is not defined

98